# Generated by Django 6.0.7 on 2026-07-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('python', 'python'), ('java', 'java'), ('javascript', 'javascript'), ('c', 'c')], default='python', max_length=200)),
                ('difficulty_level', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=200)),
                ('notes', models.TextField(null=True)),
                ('topic', models.CharField(max_length=200)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('sample_input', models.TextField()),
                ('sample_output', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
