# Generated by Django 6.0.7 on 2026-07-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question_id', models.IntegerField()),
                ('points', models.PositiveBigIntegerField(null=True)),
                ('owner', models.CharField(max_length=200)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(null=True)),
            ],
        ),
    ]
