# Generated by Django 6.0.7 on 2026-08-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
